version: '3.8'
services:
  pocketbase:
    build: ./backend
    volumes:
      - pocketbase_data:/pb/data
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
volumes:
  pocketbase_data:
